# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NormalizeD <- function(rawdata) {
    .Call('PPtreeCR_NormalizeD', PACKAGE = 'PPtreeCR', rawdata)
}

NormalizeProjV <- function(proj) {
    .Call('PPtreeCR_NormalizeProjV', PACKAGE = 'PPtreeCR', proj)
}

FindMaxID <- function(X) {
    .Call('PPtreeCR_FindMaxID', PACKAGE = 'PPtreeCR', X)
}

LDAindex1 <- function(projclass, projdata) {
    .Call('PPtreeCR_LDAindex1', PACKAGE = 'PPtreeCR', projclass, projdata)
}

LDAindex2 <- function(projclass, projdata) {
    .Call('PPtreeCR_LDAindex2', PACKAGE = 'PPtreeCR', projclass, projdata)
}

Lpindex <- function(projclass, projdata, r) {
    .Call('PPtreeCR_Lpindex', PACKAGE = 'PPtreeCR', projclass, projdata, r)
}

PDAindex1 <- function(projclass, projdata, lambda) {
    .Call('PPtreeCR_PDAindex1', PACKAGE = 'PPtreeCR', projclass, projdata, lambda)
}

PDAindex2 <- function(projclass, projdata, lambda) {
    .Call('PPtreeCR_PDAindex2', PACKAGE = 'PPtreeCR', projclass, projdata, lambda)
}

GINIindex1D <- function(projclass, projdata) {
    .Call('PPtreeCR_GINIindex1D', PACKAGE = 'PPtreeCR', projclass, projdata)
}

ENTROPYindex1D <- function(projclass, projdata) {
    .Call('PPtreeCR_ENTROPYindex1D', PACKAGE = 'PPtreeCR', projclass, projdata)
}

PPoptimize1D <- function(origclass, origdata, method, r = 1L, lambda = 0, TOL = 0.00001, maxiter = 5000L) {
    .Call('PPtreeCR_PPoptimize1D', PACKAGE = 'PPtreeCR', origclass, origdata, method, r, lambda, TOL, maxiter)
}

PPoptimizeqD <- function(origclass, origdata, method, q, r = 1L, lambda = 0, TOL = 0.00001, maxiter = 5000L) {
    .Call('PPtreeCR_PPoptimizeqD', PACKAGE = 'PPtreeCR', origclass, origdata, method, q, r, lambda, TOL, maxiter)
}

PPoptimizeAnnealqD <- function(origclass, origdata, method, q, r = 1L, lambda = 0, TOL = 0.001, maxiter = 500000L, energy = 0.01, cooling = 0.999) {
    .Call('PPtreeCR_PPoptimizeAnnealqD', PACKAGE = 'PPtreeCR', origclass, origdata, method, q, r, lambda, TOL, maxiter, energy, cooling)
}

SPSoptimize1D <- function(origclass, origdata, method, r = 1L, lambda = 0.7, maxiter = 100L, maxN = 50L) {
    .Call('PPtreeCR_SPSoptimize1D', PACKAGE = 'PPtreeCR', origclass, origdata, method, r, lambda, maxiter, maxN)
}

SPSoptimizeqD <- function(origclass, origdata, method, q, r = 1L, lambda = 0.7, maxiter = 100L, maxN = 50L) {
    .Call('PPtreeCR_SPSoptimizeqD', PACKAGE = 'PPtreeCR', origclass, origdata, method, q, r, lambda, maxiter, maxN)
}

TRIBESoptimize1D <- function(origclass, origdata, method, r, lambda, maxiter, TOL) {
    .Call('PPtreeCR_TRIBESoptimize1D', PACKAGE = 'PPtreeCR', origclass, origdata, method, r, lambda, maxiter, TOL)
}

